### PR TITLE
Project directory structuring proposal

### PR DESCRIPTION
**Pull request by bernhard-thiele**
It is a bit similar to the structure used in FMIL which I think is rather good.

### CODE REVIEW

**Comment by lochel** [comment]
I also think that the project structure could be improved.
* We could use GitHub wiki to document the project and include it as git submodule.
* We could create a new repository, e.g. OMSimulator-testsuite, to collect test FMUs, unit tests and other test cases.
* If needed, we could move omsl and simulator together into a src directory.

Therewith, the structure would look like this:
- 3rdParty [OMSimulator-3rdParty as submodule]
- doc [GitHub wiki as submodule]
- src
  - omsl
  - simulator
- testsuite [OMSimulator-testsuite as submodule]

**Comment by lochel** [comment]
I've just created [lochel/OMSimulator-testsuite](https://github.com/lochel/OMSimulator-testsuite) as an example how the testsuite might look. (Still without directory structuring.)

**Comment by lochel** [comment]
I've also discussed this briefly with @adrpo and I've pushed now the following initial structuring:
* 3rdParty [OMSimulator-3rdParty as submodule]
* library
* simulator
* testsuite [OMSimulator-testsuite as submodule]

And the following files will be generated:
* build/bin/OMSimulator[.exe]
* build/lib/libOMSimulator.a
* build/include/OMSimulator.h

**Comment by bernhard-thiele** [comment]
Okay, more this is a more flat structure. I was thinking more in the line of the FMIlibrary where they have all source "modules" below the folder src. I think if the number of modules grows, this looks a bit more tidy. Under `tests` or `testsuite` one can then replicate the module structure. Similar to

- 3rdParty
- build [generated files]
  - bin
  - lib
  - include
- doc [Project and API documentation possibly generated with Doxygen]
- examples or tutorials [Direct usage examples from which users can learn, maybe also as submodule]
- src
  - CAPI [The C API as one module, similar for other modules]
    - include [public interface of module]
    - src [sources and internal interfaces of module]
  - OMSimulator [The "main" executable]
  - JavaAPI
  - Util
  - ...
- tests or testsuite [(unit) tests for the modules]
  - CAPI
  - OMSImulator
  - JavaAPI
  - Util
  - ...

I have played with building the project using cmake (https://github.com/bernhard-thiele/OMSimulator/tree/bth-omsim). The structure is just the one that I started with, but that can be easily adapted to anything else. The current version probably doesn't work with Visual Studio, due to the way the integration of FMIlibrary as external dependency is done. However, I guess one can find a solution to it.
 
I haven't thought much on the testsuite, yet. Besides traditional style unit tests, there is the need to accommodate large binary files for reference simulation results and test FMUs. It's good to have it as a submodule, so whatever we do there, it will not blow up the size of the main git project.

**Pull request closed without merging**
